### ISSUE TITLE
Import error for ConvODENet but not ODENet

### ISSUE THREAD

**Issue by anandijain** [EmilienDupont/augmented-neural-odes#1]
I was following the README instructions, however, I get an ImportError "cannot import name 'ConvODENet'.

```
import torch
from anode.models import ODENet, ConvODENet
```

I do not have a solution, but some preliminary google's indicate that there might be a circular dependency [stackoverflow post](https://stackoverflow.com/questions/9252543/importerror-cannot-import-name-x).

**Comment by anandijain** [comment]
I believe the correct code should be:
`from anode.conv_models import ConvODENet`

**Comment by EmilienDupont** [comment]
Yes you are completely right, I've fixed it now. Thanks!

**Comment by LinzheCAI** [comment]
I try to run experiments_img.py but got the ModuleNotFoundError: No module named 'anode'. I cannot even simplily pip install it from anaconda, as shown "Could not find a version that satisfies the requirement anode". If anyone can give some suggestion would very helpful.
